#!/usr/bin/env bash

cron_apply() {
  bash "$REPO_ROOT/plugin/scripts/cron-apply.sh" "$@"
}

cron_line() {
  grep -v '^#' "$CRON_FILE" | grep -v '^[[:space:]]*$' | head -n1
}

cron_schedule() {
  cron_line | awk '{print $1, $2, $3, $4, $5}'
}

test_daily_schedule_expression() {
  write_cfg SCHEDULE=daily HOUR=3 MINUTE=0
  cron_apply
  assert_eq "$(cron_schedule)" "0 3 * * *"
}

test_hourly_schedule_expression() {
  write_cfg SCHEDULE=hourly MINUTE=30
  cron_apply
  assert_eq "$(cron_schedule)" "30 * * * *"
}

test_weekly_schedule_expression() {
  write_cfg SCHEDULE=weekly HOUR=4 MINUTE=15 DAY_OF_WEEK=6
  cron_apply
  assert_eq "$(cron_schedule)" "15 4 * * 6"
}

test_monthly_schedule_expression() {
  write_cfg SCHEDULE=monthly HOUR=2 MINUTE=5 DAY_OF_MONTH=28
  cron_apply
  assert_eq "$(cron_schedule)" "5 2 28 * *"
}

test_custom_schedule_expression_passes_through() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="*/15 2-5 * * 1,3"
  cron_apply
  assert_eq "$(cron_schedule)" "*/15 2-5 * * 1,3"
}

test_cron_line_invokes_the_prune_script() {
  write_cfg SCHEDULE=daily
  cron_apply
  assert_contains "$(cron_line)" "/scripts/image-prune.sh"
}

test_cron_file_carries_a_generated_warning() {
  write_cfg
  cron_apply
  assert_contains "$(cat "$CRON_FILE")" "Generated by the Docker Cleanup plugin"
}

test_apply_calls_update_cron() {
  write_cfg
  cron_apply
  assert_contains "$(stub_log)" "update_cron"
}

test_disabled_removes_fragment_and_calls_update_cron() {
  write_cfg ENABLED=yes
  cron_apply
  assert_file_exists "$CRON_FILE"
  write_cfg ENABLED=no
  cron_apply
  assert_file_missing "$CRON_FILE"
  assert_contains "$(stub_log)" "update_cron"
}

test_disable_flag_removes_fragment_without_config() {
  write_cfg ENABLED=yes
  cron_apply
  assert_file_exists "$CRON_FILE"
  rm -f "$CFG_FILE"
  cron_apply --disable
  assert_file_missing "$CRON_FILE"
}

test_missing_update_cron_is_a_loud_failure() {
  write_cfg
  rm -f "$UPDATE_CRON"
  local out status
  out="$(cron_apply 2>&1)"
  status=$?
  assert_status "$status" 1
  assert_contains "$out" "update_cron"
}

test_invalid_custom_cron_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="not a cron line"
  local out status
  out="$(cron_apply 2>&1)"
  status=$?
  assert_status "$status" 1
  assert_contains "$out" "cron"
}

test_custom_cron_with_wrong_field_count_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 3 * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_out_of_range_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 99 * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_with_shell_metacharacters_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON='0 3 * * * ; rm -rf /'
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_invalid_config_leaves_existing_fragment_intact() {
  write_cfg SCHEDULE=daily HOUR=3 MINUTE=0
  cron_apply
  local before
  before="$(cat "$CRON_FILE")"
  write_cfg SCHEDULE=custom CUSTOM_CRON="garbage"
  cron_apply >/dev/null 2>&1
  assert_file_exists "$CRON_FILE"
  assert_eq "$(cat "$CRON_FILE")" "$before"
}

test_out_of_range_hour_is_rejected() {
  write_cfg SCHEDULE=daily HOUR=24
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_day_of_month_above_28_is_rejected() {
  write_cfg SCHEDULE=monthly DAY_OF_MONTH=31
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_unknown_schedule_is_rejected() {
  write_cfg SCHEDULE=fortnightly
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_validate_only_changes_nothing() {
  write_cfg SCHEDULE=daily
  local status
  cron_apply --validate-only --cfg "$CFG_FILE"
  status=$?
  assert_status "$status" 0
  assert_file_missing "$CRON_FILE"
  assert_not_contains "$(stub_log)" "update_cron"
}

test_validate_only_reports_invalid_config() {
  write_cfg SCHEDULE=daily MINUTE=61
  local status
  cron_apply --validate-only --cfg "$CFG_FILE" >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}
