#!/usr/bin/env bash

cron_apply() {
  bash "$REPO_ROOT/plugin/scripts/cron-apply.sh" "$@"
}

cron_line() {
  grep -v '^#' "$CRON_FILE" | grep -v '^[[:space:]]*$' | head -n1
}

cron_schedule() {
  cron_line | awk '{print $1, $2, $3, $4, $5}'
}

test_daily_schedule_expression() {
  write_cfg SCHEDULE=daily HOUR=3 MINUTE=0
  cron_apply
  assert_eq "$(cron_schedule)" "0 3 * * *"
}

test_hourly_schedule_expression() {
  write_cfg SCHEDULE=hourly MINUTE=30
  cron_apply
  assert_eq "$(cron_schedule)" "30 * * * *"
}

test_weekly_schedule_expression() {
  write_cfg SCHEDULE=weekly HOUR=4 MINUTE=15 DAY_OF_WEEK=6
  cron_apply
  assert_eq "$(cron_schedule)" "15 4 * * 6"
}

test_monthly_schedule_expression() {
  write_cfg SCHEDULE=monthly HOUR=2 MINUTE=5 DAY_OF_MONTH=28
  cron_apply
  assert_eq "$(cron_schedule)" "5 2 28 * *"
}

test_custom_schedule_expression_passes_through() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="*/15 2-5 * * 1,3"
  cron_apply
  assert_eq "$(cron_schedule)" "*/15 2-5 * * 1,3"
}

test_cron_line_invokes_the_prune_script() {
  write_cfg SCHEDULE=daily
  cron_apply
  assert_contains "$(cron_line)" "/scripts/image-prune.sh"
}

test_cron_file_carries_a_generated_warning() {
  write_cfg
  cron_apply
  assert_contains "$(cat "$CRON_FILE")" "Generated by the Docker Cleanup plugin"
}

test_apply_calls_update_cron() {
  write_cfg
  cron_apply
  assert_contains "$(stub_log)" "update_cron"
}

test_disabled_removes_fragment_and_calls_update_cron() {
  write_cfg ENABLED=yes
  cron_apply
  assert_file_exists "$CRON_FILE"
  write_cfg ENABLED=no
  cron_apply
  assert_file_missing "$CRON_FILE"
  assert_contains "$(stub_log)" "update_cron"
}

test_disable_flag_removes_fragment_and_calls_update_cron() {
  # --disable is the uninstall contract: it must remove the fragment AND
  # rebuild the system crontab, not just tidy up flash. The config is left in
  # place, matching real uninstall (AGENTS.md: the .cfg stays on flash), so
  # this can't be satisfied by --disable silently falling through to the
  # ENABLED=no default path instead of its own branch.
  write_cfg ENABLED=yes
  cron_apply
  assert_file_exists "$CRON_FILE"
  : > "$STUB_LOG"
  cron_apply --disable
  assert_file_missing "$CRON_FILE"
  assert_contains "$(stub_log)" "update_cron"
}

test_disable_flag_works_with_no_config_at_all() {
  # The uninstaller must be able to stop the job even when the config is
  # missing or unreadable, which is why --disable short-circuits before
  # load_cfg. Deleting the cfg here is what pins that ordering: if --disable
  # ever moved below load_cfg, this is the test that catches it.
  write_cfg ENABLED=yes
  cron_apply
  assert_file_exists "$CRON_FILE"
  rm -f "$CFG_FILE"
  : > "$STUB_LOG"
  local status
  cron_apply --disable
  status=$?
  assert_status "$status" 0
  assert_file_missing "$CRON_FILE"
  assert_contains "$(stub_log)" "update_cron"
}

test_disable_flag_works_with_an_unreadable_config() {
  # Same contract, the other way a config goes bad: garbage that would fail
  # validation must not block the disable.
  write_cfg ENABLED=yes
  cron_apply
  assert_file_exists "$CRON_FILE"
  printf 'SCHEDULE="custom"\nCUSTOM_CRON="not a cron line"\n' > "$CFG_FILE"
  : > "$STUB_LOG"
  local status
  cron_apply --disable
  status=$?
  assert_status "$status" 0
  assert_file_missing "$CRON_FILE"
  assert_contains "$(stub_log)" "update_cron"
}

test_missing_update_cron_is_a_loud_failure() {
  write_cfg
  rm -f "$UPDATE_CRON"
  local out status
  out="$(cron_apply 2>&1)"
  status=$?
  assert_status "$status" 1
  assert_contains "$out" "update_cron"
}

test_invalid_custom_cron_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="not a cron line"
  local out status
  out="$(cron_apply 2>&1)"
  status=$?
  assert_status "$status" 1
  assert_contains "$out" "cron"
}

test_custom_cron_with_wrong_field_count_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 3 * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_out_of_range_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 99 * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_with_shell_metacharacters_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON='0 3 * * * ; rm -rf /'
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_invalid_config_leaves_existing_fragment_intact() {
  write_cfg SCHEDULE=daily HOUR=3 MINUTE=0
  cron_apply
  local before
  before="$(cat "$CRON_FILE")"
  write_cfg SCHEDULE=custom CUSTOM_CRON="garbage"
  cron_apply >/dev/null 2>&1
  assert_file_exists "$CRON_FILE"
  assert_eq "$(cat "$CRON_FILE")" "$before"
}

test_out_of_range_hour_is_rejected() {
  write_cfg SCHEDULE=daily HOUR=24
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_day_of_month_above_28_is_rejected() {
  write_cfg SCHEDULE=monthly DAY_OF_MONTH=31
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_unknown_schedule_is_rejected() {
  write_cfg SCHEDULE=fortnightly
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_validate_only_changes_nothing() {
  write_cfg SCHEDULE=daily
  local status
  cron_apply --validate-only --cfg "$CFG_FILE"
  status=$?
  assert_status "$status" 0
  assert_file_missing "$CRON_FILE"
  assert_not_contains "$(stub_log)" "update_cron"
}

test_validate_only_reports_invalid_config() {
  write_cfg SCHEDULE=daily MINUTE=61
  local status
  cron_apply --validate-only --cfg "$CFG_FILE" >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

# --- Regression coverage added after adversarial review ---

test_custom_cron_trailing_comma_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="1,2, 3 * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_leading_comma_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON=",1,2 3 * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_doubled_comma_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="1,,2 3 * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_multi_hyphen_range_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 1-5-9 * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_reversed_range_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 5-2 * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_range_missing_lower_bound_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 -5 * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_range_missing_upper_bound_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 5- * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_step_zero_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="*/0 * * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_step_too_large_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="*/60 * * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_integer_overflow_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="18446744073709551616 * * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_preset_minute_integer_overflow_is_rejected() {
  write_cfg SCHEDULE=daily MINUTE=18446744073709551616
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_over_long_custom_expression_is_rejected() {
  local long_field="" i
  for i in $(seq 1 100); do
    long_field+="$(( i % 60 )),"
  done
  long_field="${long_field%,}"
  write_cfg SCHEDULE=custom CUSTOM_CRON="$long_field * * * *"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_day_of_week_seven_is_accepted() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 3 * * 7"
  cron_apply
  assert_eq "$(cron_schedule)" "0 3 * * 7"
}

test_custom_cron_day_of_week_eight_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 3 * * 8"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_leading_zero_is_accepted_and_preserved() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="08 3 * * *"
  cron_apply
  assert_eq "$(cron_schedule)" "08 3 * * *"
}

test_custom_cron_empty_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON=""
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_whitespace_only_is_rejected() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="   "
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_validate_only_rejects_missing_cfg_file() {
  local status
  cron_apply --validate-only --cfg "$TMP/does-not-exist.cfg" >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

# --- Accept-case regressions: the fixes above must not start rejecting
# valid expressions. ---

test_custom_cron_range_with_step_is_accepted() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="1-10/2 * * * *"
  cron_apply
  assert_eq "$(cron_schedule)" "1-10/2 * * * *"
}

test_custom_cron_wildcard_step_is_accepted() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="*/15 * * * *"
  cron_apply
  assert_eq "$(cron_schedule)" "*/15 * * * *"
}

test_custom_cron_sunday_zero_is_accepted() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="0 3 * * 0"
  cron_apply
  assert_eq "$(cron_schedule)" "0 3 * * 0"
}

test_custom_cron_all_wildcards_is_accepted() {
  write_cfg SCHEDULE=custom CUSTOM_CRON="* * * * *"
  cron_apply
  assert_eq "$(cron_schedule)" "* * * * *"
}

# --- Regression coverage: CUSTOM_CRON is validated regardless of which
# schedule is active, so a stale value can never round-trip onto flash. ---

test_custom_cron_is_validated_even_when_schedule_is_not_custom() {
  write_cfg SCHEDULE=daily CUSTOM_CRON="not a cron line"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_custom_cron_backslash_is_rejected_regardless_of_schedule() {
  local trailing_backslash
  trailing_backslash=$'a\\'   # literal a followed by one backslash
  write_cfg SCHEDULE=daily "CUSTOM_CRON=$trailing_backslash"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  assert_status "$status" 1
}

test_empty_custom_cron_is_fine_when_schedule_is_not_custom() {
  write_cfg SCHEDULE=daily CUSTOM_CRON=""
  cron_apply
  assert_eq "$(cron_schedule)" "0 3 * * *"
}

test_write_failure_is_reported_not_swallowed() {
  write_cfg SCHEDULE=daily
  chmod 555 "$BOOT_CONFIG"
  local status
  cron_apply >/dev/null 2>&1
  status=$?
  chmod 755 "$BOOT_CONFIG"
  assert_status "$status" 1
}
